0|Catppuccin-Mocha|~/.config/swww/Catppuccin-Mocha/aesthetic_deer.png
0|Catppuccin-Latte|~/.config/swww/Catppuccin-Latte/jormungandr.jpg
1|Decay-Green|~/.config/swww/Decay-Green/pixlr-generated.png
0|Rose-Pine|~/.config/swww/Rose-Pine/ferris_wheel.jpg
0|Tokyo-Night|~/.config/swww/Tokyo-Night/tokyo_pink.png
0|Material-Sakura|~/.config/swww/Material-Sakura/material_pastel_6.jpg
0|Material-Sakura|~/.config/swww/Material-Sakura/material_pastel_7.jpg
0|Cyberpunk-Edge|~/.config/swww/Cyberpunk-Edge/lucy_1.jpg
0|Frosted-Glass|~/.config/swww/Frosted-Glass/min_forest.jpg
0|Frosted-Glass|~/.config/swww/Frosted-Glass/blue_desert.png
