0|Catppuccin-Mocha|~/.config/swww/Catppuccin-Mocha/space_saturn.png
0|Catppuccin-Latte|~/.config/swww/Catppuccin-Latte/jormungandr.jpg
1|Decay-Green|~/.config/swww/Decay-Green/pixlr-generated.png
0|Rose-Pine|~/.config/swww/Rose-Pine/mountain_dragon_pink.jpg
0|Tokyo-Night|~/.config/swww/Tokyo-Night/tokyo_pink.png
0|Material-Sakura|~/.config/swww/Material-Sakura/material_pastel_4.jpg
0|Graphite-Mono|~/.config/swww/Graphite-Mono/spring_bloom.jpg
0|Cyberpunk-Edge|~/.config/swww/Cyberpunk-Edge/david.jpg
0|Frosted-Glass|~/.config/swww/Frosted-Glass/cloudy_mountain.png
0|Gruvbox-Retro|~/.config/swww/Gruvbox-Retro/street.png
