general {
    col.active_border = rgba(#6A1927ff) rgba(#D77686ff) 45deg
    col.inactive_border = rgba(#AC3E51cc) rgba(#F1D6DBcc) 45deg
}

group {
    col.border_active = rgba(#6A1927ff) rgba(#D77686ff) 45deg
    col.border_inactive = rgba(#AC3E51cc) rgba(#F1D6DBcc) 45deg
    col.border_locked_active = rgba(#6A1927ff) rgba(#D77686ff) 45deg
    col.border_locked_inactive = rgba(#AC3E51cc) rgba(#F1D6DBcc) 45deg
}
