
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█


# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = match:class ^(firefox)$ opacity 0.90 0.90
windowrule = match:class ^(Brave-browser)$ opacity 0.90 0.90
windowrule = match:class ^(Steam)$ opacity 0.80 0.80
windowrule = match:class ^(steam)$ opacity 0.80 0.80
windowrule = match:class ^(steamwebhelper)$ opacity 0.80 0.80
windowrule = match:class ^(Spotify)$ opacity 0.80 0.80
windowrule = match:class ^(Code)$ opacity 0.80 0.80
windowrule = match:class ^(code-url-handler)$ opacity 0.80 0.80
windowrule = match:class ^(kitty)$ opacity 0.80 0.80
windowrule = match:class ^(org.kde.dolphin)$ opacity 0.80 0.80
windowrule = match:class ^(org.kde.ark)$ opacity 0.80 0.80
windowrule = match:class ^(nwg-look)$ opacity 0.80 0.80
windowrule = match:class ^(qt5ct)$ opacity 0.80 0.80

windowrule = match:class ^(com.github.rafostar.Clapper)$ opacity 0.90 0.90 #Clapper-Gtk
windowrule = match:class ^(com.github.tchx84.Flatseal)$ opacity 0.80 0.80 #Flatseal-Gtk
windowrule = match:class ^(hu.kramo.Cartridges)$ opacity 0.80 0.80 #Cartridges-Gtk
windowrule = match:class ^(com.obsproject.Studio)$ opacity 0.80 0.80 #Obs-Qt
windowrule = match:class ^(gnome-boxes)$ opacity 0.80 0.80 #Boxes-Gtk
windowrule = match:class ^(discord)$ opacity 0.80 0.80 #Discord-Electron
windowrule = match:class ^(WebCord)$ opacity 0.80 0.80 #WebCord-Electron
windowrule = match:class ^(app.drey.Warp)$ opacity 0.80 0.80 #Warp-Gtk
windowrule = match:class ^(net.davidotek.pupgui2)$ opacity 0.80 0.80 #ProtonUp-Qt
windowrule = match:class ^(yad)$ opacity 0.80 0.80 #Protontricks-Gtk
windowrule = match:class ^(Signal)$ opacity 0.80 0.80 #Signal-Gtk
windowrule = match:class ^(io.gitlab.theevilskeleton.Upscaler)$ opacity 0.80 0.80 #Upscaler-Gtk

windowrule = match:class ^(pavucontrol)$ opacity 0.80 0.70
windowrule = match:class ^(blueman-manager)$ opacity 0.80 0.70
windowrule = match:class ^(nm-applet)$ opacity 0.80 0.70
windowrule = match:class ^(nm-connection-editor)$ opacity 0.80 0.70
windowrule = match:class ^(org.kde.polkit-kde-authentication-agent-1)$ opacity 0.80 0.70

windowrule = match:class ^(qt5ct)$ float
windowrule = match:class ^(nwg-look)$ float
windowrule = match:class ^(org.kde.ark)$ float
windowrule = match:class ^(Signal)$ float #Signal-Gtk
windowrule = match:class ^(com.github.rafostar.Clapper)$ float #Clapper-Gtk
windowrule = match:class ^(app.drey.Warp)$ float #Warp-Gtk
windowrule = match:class ^(net.davidotek.pupgui2)$ float #ProtonUp-Qt
windowrule = match:class ^(yad)$ float #Protontricks-Gtk
windowrule = match:class ^(eog)$ float #Imageviewer-Gtk
windowrule = match:class ^(io.gitlab.theevilskeleton.Upscaler)$ float #Upscaler-Gtk
windowrule = match:class ^(pavucontrol)$ float
windowrule = match:class ^(blueman-manager)$ float
windowrule = match:class ^(nm-applet)$ float
windowrule = match:class ^(nm-connection-editor)$ float
windowrule = match:class ^(org.kde.polkit-kde-authentication-agent-1)$ float
