hl.windowrule = {
    -- Opacity rules
    { rule = "match:class ^(firefox)$",                                   property = "opacity", value = { 0.90, 0.90 } },
    { rule = "match:class ^(Brave-browser)$",                             property = "opacity", value = { 0.90, 0.90 } },
    { rule = "match:class ^(Steam)$",                                     property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(steam)$",                                     property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(steamwebhelper)$",                            property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(Spotify)$",                                   property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(Code)$",                                      property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(code-url-handler)$",                          property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(kitty)$",                                     property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(org.kde.dolphin)$",                           property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(org.kde.ark)$",                               property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(nwg-look)$",                                  property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(qt5ct)$",                                     property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(com.github.rafostar.Clapper)$",               property = "opacity", value = { 0.90, 0.90 } },
    { rule = "match:class ^(com.github.tchx84.Flatseal)$",                property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(hu.kramo.Cartridges)$",                       property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(com.obsproject.Studio)$",                     property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(gnome-boxes)$",                               property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(discord)$",                                   property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(WebCord)$",                                   property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(app.drey.Warp)$",                             property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(net.davidotek.pupgui2)$",                     property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(yad)$",                                       property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(Signal)$",                                    property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(io.gitlab.theevilskeleton.Upscaler)$",        property = "opacity", value = { 0.80, 0.80 } },
    { rule = "match:class ^(pavucontrol)$",                               property = "opacity", value = { 0.80, 0.70 } },
    { rule = "match:class ^(blueman-manager)$",                           property = "opacity", value = { 0.80, 0.70 } },
    { rule = "match:class ^(nm-applet)$",                                 property = "opacity", value = { 0.80, 0.70 } },
    { rule = "match:class ^(nm-connection-editor)$",                      property = "opacity", value = { 0.80, 0.70 } },
    { rule = "match:class ^(org.kde.polkit-kde-authentication-agent-1)$", property = "opacity", value = { 0.80, 0.70 } },

    -- Float rules
    { rule = "match:class ^(qt5ct)$",                                     property = "float",   value = true },
    { rule = "match:class ^(nwg-look)$",                                  property = "float",   value = true },
    { rule = "match:class ^(org.kde.ark)$",                               property = "float",   value = true },
    { rule = "match:class ^(Signal)$",                                    property = "float",   value = true },
    { rule = "match:class ^(com.github.rafostar.Clapper)$",               property = "float",   value = true },
    { rule = "match:class ^(app.drey.Warp)$",                             property = "float",   value = true },
    { rule = "match:class ^(net.davidotek.pupgui2)$",                     property = "float",   value = true },
    { rule = "match:class ^(yad)$",                                       property = "float",   value = true },
    { rule = "match:class ^(eog)$",                                       property = "float",   value = true },
    { rule = "match:class ^(io.gitlab.theevilskeleton.Upscaler)$",        property = "float",   value = true },
    { rule = "match:class ^(pavucontrol)$",                               property = "float",   value = true },
    { rule = "match:class ^(blueman-manager)$",                           property = "float",   value = true },
    { rule = "match:class ^(nm-applet)$",                                 property = "float",   value = true },
    { rule = "match:class ^(nm-connection-editor)$",                      property = "float",   value = true },
    { rule = "match:class ^(org.kde.polkit-kde-authentication-agent-1)$", property = "float",   value = true }
}
